sudo: required
language: rust
cache: cargo

# feature rust-1-31 is only used to enable more lints checked by rustc and clippy
# feature mocking is needed to execute tests with mocking
matrix:
  include:
    - rust: nightly
      env: FEATURES="rust-1-31 mocking"
      before_script:
        - rustup component add clippy-preview || return 0
        - rustup component add rustfmt-preview || return 0
      before_cache:
        - cargo install cargo-update || echo "cargo-update already installed"
        - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin || echo "cargo-tarpaulin already installed"
        - cargo install-update cargo-update
        - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install-update cargo-tarpaulin
      after_success:
        - RUST_BACKTRACE=full cargo tarpaulin --out Xml
        - bash <(curl -s https://codecov.io/bash)
    - rust: beta
      env: FEATURES=rust-1-31
    - rust: stable
      env: FEATURES=rust-1-31
    - rust: 1.27.0 # current stable version in nixpkgs
      env: FEATURES=

    - language: nix
      name: nix build on nixpkgs-unstable
      before_script:
        - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
        - nix-channel --update
        - nix eval nixpkgs.rustc.version
      script:
        # use nix-build because travis bulid get killed after 10 minutes without output
        # - nix build --verbose
        - nix-build
    # disabled because of missing edition feature required by Mocktopus
    # - language: nix
    #   name: nix build on nixos-18.09
    #   before_script:
    #     - nix-channel --add https://nixos.org/channels/nixos-18.09 nixpkgs
    #     - nix-channel --update
    #     - nix eval nixpkgs.rustc.version
    #   script:
    #     - nix build --verbose

script:
  - |
    if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]] && hash cargo-fmt 2> /dev/null; then
      cargo fmt -- --verbose --check
    fi
  - cargo check --verbose --features "$FEATURES"
  - cargo build --verbose --features "$FEATURES"
  - |
    if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]] && hash cargo-clippy 2> /dev/null; then
      cargo clippy --verbose --features "$FEATURES"
    fi
  - cargo test --verbose --features "$FEATURES"

addons:
  apt:
    packages:
      - libdbus-1-dev
      - libgdk-pixbuf2.0-dev
      - libglib2.0-dev
      - libnotify-dev
      - libssl-dev # for tarpaulin
