combine_control_expr = false
comment_width = 100
condense_wildcard_suffixes = true
format_doc_comments = true
format_macro_bodies = true
format_strings = true
match_block_trailing_comma = true
max_width = 100
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
