debug = false
order = []
separator = " / "

[audio]
control = "Master"
mute = "MUTE"
template = "S {VOL}%"
icons = []

[backlight]
device = "intel_backlight"
template = "L {BL}%"

[battery]
charging = "▲"
discharging = "▼"
enable_notifier = true
no_battery = "NO BATT"
notifier_critical = 10
notifier_levels = [2, 5, 10, 15, 20]
separator = " · "

[cpu_load]
template = "{CL1} {CL5} {CL15}"
update_interval = 20

[time]
format = "%Y-%m-%d %H:%M"
update_seconds = false
